dtb-$(CONFIG_MACH_XIAOMI_VINCE) += mi8953/msm8953-vince.dtb
dtb-$(CONFIG_MACH_XIAOMI_YSL) += mi8953/msm8953-ysl.dtb
dtb-$(CONFIG_MACH_XIAOMI_MIDO) += mi8953/msm8953-mido.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
